// Recording storage. Filesystem only, on purpose.
//
// Conversation video is study data under IRB 2020-1657 and must land on UW
// Research Drive — never a cloud bucket, never the app database. On the UW
// server RECORDING_DIR points at the mounted Research Drive share; locally it
// points at a scratch folder so the pipeline can be exercised without one.
//
// Files are never served from a public path: reads go through an authenticated
// route handler, so RECORDING_DIR must live outside the web root.

import "server-only";
import { createReadStream } from "node:fs";
import { appendFile, mkdir, rm, stat } from "node:fs/promises";
import { dirname, join, normalize, resolve, sep } from "node:path";

export function recordingRoot(): string {
  const dir = process.env.RECORDING_DIR;
  if (!dir) {
    throw new Error(
      "RECORDING_DIR is not set — point it at the Research Drive mount (or a local folder in dev)."
    );
  }
  return resolve(dir);
}

export function isStorageConfigured(): boolean {
  return Boolean(process.env.RECORDING_DIR);
}

/**
 * Resolves a storage key to an absolute path, refusing anything that escapes
 * the root. Keys are generated by storageKeyFor() rather than user input, but
 * they reach here through a request body, so this stays a hard boundary.
 */
export function resolveKey(key: string): string {
  const root = recordingRoot();
  const full = resolve(join(root, normalize(key)));
  if (full !== root && !full.startsWith(root + sep)) {
    throw new Error("Invalid storage key.");
  }
  return full;
}

/**
 * Appends one chunk of a recording, creating the file on first write.
 * MediaRecorder produces a stream of blobs; appending keeps memory flat
 * regardless of how long the conversation runs.
 */
export async function appendChunk(key: string, chunk: Buffer): Promise<void> {
  const path = resolveKey(key);
  await mkdir(dirname(path), { recursive: true });
  await appendFile(path, chunk);
}

export async function fileSize(key: string): Promise<number> {
  try {
    return (await stat(resolveKey(key))).size;
  } catch {
    return 0;
  }
}

export async function fileExists(key: string): Promise<boolean> {
  try {
    await stat(resolveKey(key));
    return true;
  } catch {
    return false;
  }
}

/** Read stream for the authenticated playback route. */
export function readStreamFor(key: string): ReturnType<typeof createReadStream> {
  return createReadStream(resolveKey(key));
}

/** Removes a partial file so a retry starts clean. */
export async function removeFile(key: string): Promise<void> {
  await rm(resolveKey(key), { force: true });
}
